version: '2.1'
services:
  web:
    build: ./web
    links:
      - db
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      timeout: 20s
      retries: 10
